### PR TITLE
Remove incorrect order direction

### PR DESCRIPTION
**Pull request by moshejs**
fixes  [#124](https://github.com/Synthetixio/stats/issues/124)

### CODE REVIEW

**Comment by moshejs** [comment]
@KillerByte 👀

**Comment by KillerByte** [comment]
hi @moshejs thanks for fixing this! will take a look, it will probably be merged later today.

**Review by KillerByte — CHANGES_REQUESTED** [review]
while the UI looks correct now, there is still a problem: the data returned by the graph should always be the *latest* 1000 not the first 1000, so as the number of liquidations increase this will become incorrect. you can see this effect on the liquidations table

instead, the data should be pulled the same as it is now, but the formatted graph data is reversed from the `formatLiquidationsData` function

**Comment by moshejs** [comment]
Thanks for the feedback + opportunity to take another look at this @KillerByte!

So I was able to find `formatLiquidationsData` on the same file, but not sure I understand where the ordering is being handled.

I could take a guess and suggest that `_.last()` on lines 82-83 would be a place to consider

**Comment by KillerByte** [comment]
@moshejs basically the problem is just that the data for the chart only is the one that is reversed (because the chart renders from left to right). therefore, the return array from that function is the most appropriate to reverse.

You can use the `_.reverse` function (or just plain js `.reverse()`

If you don't reverse from that location, it reverses the data in the table, which is not what we want.

Let me know if you have any other questions!

**Comment by moshejs** [comment]
@KillerByte - changes pushed !

**Review by KillerByte — APPROVED** [review]
thanks!

**Comment by moshejs** [comment]
@KillerByte do you have everything you need to conduct the merge?

**Comment by KillerByte** [comment]
should be merged into master (live) next week

**Pull request merged**
