### PR TITLE
Jwineman/translations

### PR DESCRIPTION
**Pull request by jwineman**
Translations for stats.

### CODE REVIEW

**Comment by jwineman** [comment]
Should I be pointing this at `staging`?

**Comment by dvd-schwrtz** [comment]
@jwineman yes, staging 👍

**Comment by dvd-schwrtz** [comment]
@jwineman please fix the CI issues. Thanks

**Comment by jwineman** [comment]
Sorry, got access to vercel now.

**Comment by dvd-schwrtz** [comment]
@jwineman The rest looks ok but `NUMBER OF TRADES` has the wrong translation. Please update. Thanks

**Pull request merged**
